apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtls-backend
  namespace: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-backend
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-backend
  template:
    metadata:
      labels:
        app: mtls-backend
    spec:
      serviceAccountName: mtls-backend
      automountServiceAccountToken: true
      containers:
        - name: app
          image: vault-spiffe-mtls-backend:local
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8443"
            - name: VAULT_ADDR
              value: https://host.docker.internal:18200
            - name: VAULT_CA_FILE
              value: /var/run/hashibank/roots/hashibank-root-ca.crt
            - name: VAULT_K8S_ROLE
              value: mtls-backend
            - name: VAULT_PKI_ROLE
              value: mtls-backend-k8s-spiffe
            - name: SERVICE_ACCOUNT_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: WORKLOAD_SPIFFE_ID
              value: spiffe://hashibank.demo/ns/payments/sa/mtls-backend
            - name: ALLOWED_CLIENT_SPIFFE_IDS
              value: spiffe://hashibank.demo/ns/payments/sa/payments-api
            - name: CERT_TTL
              value: 8h
            - name: COMMON_NAME
              value: mtls-backend.payments.svc.cluster.local
            - name: SERVER_CERT_FILE
              value: /var/run/hashibank/identity/tls.crt
            - name: SERVER_KEY_FILE
              value: /var/run/hashibank/identity/tls.key
            - name: CLIENT_CA_FILE
              value: /var/run/hashibank/client-ca/hashibank-spiffe-root.pem
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: identity
              mountPath: /var/run/hashibank/identity
            - name: roots
              mountPath: /var/run/hashibank/roots
              readOnly: true
            - name: client-ca
              mountPath: /var/run/hashibank/client-ca
              readOnly: true
      volumes:
        - name: identity
          emptyDir: {}
        - name: roots
          configMap:
            name: hashibank-root-ca
        - name: client-ca
          configMap:
            name: hashibank-spiffe-root
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-backend
  namespace: payments
spec:
  selector:
    app: mtls-backend
  ports:
    - name: https
      port: 8443
      targetPort: https
