apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api
  namespace: payments
---
apiVersion: v1
kind: Pod
metadata:
  name: payments-api
  namespace: payments
  labels:
    app: payments-api
spec:
  serviceAccountName: payments-api
  automountServiceAccountToken: true
  containers:
    - name: workload
      image: vault-spiffe-demo-tools:local
      imagePullPolicy: Never
      command: ["bash", "-lc", "sleep infinity"]
      volumeMounts:
        - name: roots
          mountPath: /var/run/hashibank/roots
          readOnly: true
        - name: spiffe-root
          mountPath: /var/run/hashibank/spiffe
          readOnly: true
  volumes:
    - name: roots
      configMap:
        name: hashibank-root-ca
    - name: spiffe-root
      configMap:
        name: hashibank-spiffe-root
