server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    socket_path = "/run/spire/server/private/api.sock"
    trust_domain = "spire.hashibank.demo"
    data_dir = "/var/lib/spire/server/.data"
    log_level = "DEBUG"

    federation {
        bundle_endpoint {
            address = "0.0.0.0"
            port = 8443
            refresh_hint = "10m"
            profile "https_web" {
                serving_cert_file {
                    cert_file_path = "/opt/spire/certs/spire-server.crt"
                    key_file_path = "/opt/spire/certs/spire-server.key"
                    file_sync_interval = "5m"
                }
            }
        }
    }
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/var/lib/spire/server/.data/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {
        }
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/var/lib/spire/server/.data/keys.json"
        }
    }

    UpstreamAuthority "vault" {
        plugin_data {
            pki_mount_point = "spire-pki"
            approle_auth {
            }
        }
    }
}
