name: vault-spiffe-demo

services:
  hashibank-vault:
    image: ${VAULT_ENTERPRISE_IMAGE:-hashicorp/vault-enterprise:2.0.0-ent}
    user: "0:0"
    cap_add:
      - IPC_LOCK
    command:
      - vault
      - server
      - -config=/vault/config/hashibank-vault.hcl
    environment:
      VAULT_LICENSE_PATH: /vault/config/license.hclic
    ports:
      - "${HASHIBANK_VAULT_HOST_PORT:-18200}:8200"
    volumes:
      - ../license.hclic:/vault/config/license.hclic:ro
      - ./config/hashibank-vault.hcl:/vault/config/hashibank-vault.hcl:ro
      - ./config/tls:/vault/config/tls
      - ./policies:/vault/policies:ro
      - ./runtime/hashibank-vault/file:/vault/file
      - ./runtime:/vault/runtime

  postgres-hashibank:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: hashibank
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./runtime/postgres:/var/lib/postgresql/data

  hashibank-fraud-web:
    build:
      context: .
      dockerfile: apps/hashibank-fraud-web/Dockerfile
    depends_on:
      - hashibank-vault
      - postgres-hashibank
    ports:
      - "${HASHIBANK_FRAUD_WEB_PORT:-18081}:8080"
    volumes:
      - ./config/tls:/workspace/tls:ro
      - ./runtime:/workspace/runtime

  hashibank-assistant:
    build:
      context: .
      dockerfile: apps/hashibank-assistant/Dockerfile
    depends_on:
      - hashibank-vault
    ports:
      - "${HASHIBANK_ASSISTANT_WEB_PORT:-18082}:8080"
    volumes:
      - ./config/tls:/workspace/tls:ro
      - ./runtime:/workspace/runtime

  demo-tools:
    build:
      context: .
      dockerfile: tools/Dockerfile
    command:
      - bash
      - -lc
      - sleep infinity
    depends_on:
      - hashibank-vault
      - postgres-hashibank
    working_dir: /workspace/demo
    volumes:
      - ../:/workspace
